config/routes.rb
Rails.application.routes.draw do
  resources :server_corpus do
    member do
      get :bind_part
    end
  end
  resources :servers
  resources :server_parts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/server.rb
class Server < ApplicationRecord
end

app/models/server_corpu.rb
class ServerCorpu < ApplicationRecord
  has_many :server_server_parts
  has_many :server_parts, through: :server_server_parts

  def bind_part(part_id)
    ServerServerPart.create(server_corpu_id: id, server_part_id: part_id)
  end

end

app/models/server_part.rb
class ServerPart < ApplicationRecord
end

app/models/server_server_part.rb
class ServerServerPart < ApplicationRecord
  belongs_to :server_part
  belongs_to :server_corpu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/server_corpus_controller.rb
class ServerCorpusController < ApplicationController
  require "rqrcode"
  before_action :set_server_corpu, only: %i[ show edit update destroy bind_part ]

  # GET /server_corpus or /server_corpus.json
  def index
    @server_corpus = ServerCorpu.all
  end

  # GET /server_corpus/1 or /server_corpus/1.json
  def show
    respond_to do |format|
      format.html
      format.png { send_data RQRCode::QRCode.new(@server_corpu.id.to_s).as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: "black",
        file: nil,
        fill: "white",
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 120
      ).to_s }
    end
  end

  # GET /server_corpus/new
  def new
    @server_corpu = ServerCorpu.new
  end

  # GET /server_corpus/1/edit
  def edit
  end

  # POST /server_corpus or /server_corpus.json
  def create
    @server_corpu = ServerCorpu.new(server_corpu_params)

    respond_to do |format|
      if @server_corpu.save
        format.html { redirect_to server_corpu_url(@server_corpu), notice: "Server corpu was successfully created." }
        format.json { render :show, status: :created, location: @server_corpu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @server_corpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /server_corpus/1 or /server_corpus/1.json
  def update
    respond_to do |format|
      if @server_corpu.update(server_corpu_params)
        format.html { redirect_to server_corpu_url(@server_corpu), notice: "Server corpu was successfully updated." }
        format.json { render :show, status: :ok, location: @server_corpu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @server_corpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_corpus/1 or /server_corpus/1.json
  def destroy
    @server_corpu.destroy

    respond_to do |format|
      format.html { redirect_to server_corpus_url, notice: "Server corpu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def bind_part
    @server_corpu.bind_part(params[:part_id])
    render json: { status: :binded }, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_server_corpu
    @server_corpu = ServerCorpu.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def server_corpu_params
    params.require(:server_corpu).permit(:name)
  end
end

app/controllers/server_parts_controller.rb
class ServerPartsController < ApplicationController
  before_action :set_server_part, only: %i[ show edit update destroy ]

  # GET /server_parts or /server_parts.json
  def index
    @server_parts = ServerPart.all
  end

  # GET /server_parts/1 or /server_parts/1.json
  def show
    respond_to do |format|
      format.html
      format.png { send_data RQRCode::QRCode.new(@server_part.id.to_s).as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: "black",
        file: nil,
        fill: "white",
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 120
      ).to_s }
    end
  end

  # GET /server_parts/new
  def new
    @server_part = ServerPart.new
  end

  # GET /server_parts/1/edit
  def edit
  end

  # POST /server_parts or /server_parts.json
  def create
    @server_part = ServerPart.new(server_part_params)

    respond_to do |format|
      if @server_part.save
        format.html { redirect_to server_part_url(@server_part), notice: "Server part was successfully created." }
        format.json { render :show, status: :created, location: @server_part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @server_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /server_parts/1 or /server_parts/1.json
  def update
    respond_to do |format|
      if @server_part.update(server_part_params)
        format.html { redirect_to server_part_url(@server_part), notice: "Server part was successfully updated." }
        format.json { render :show, status: :ok, location: @server_part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @server_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_parts/1 or /server_parts/1.json
  def destroy
    @server_part.destroy

    respond_to do |format|
      format.html { redirect_to server_parts_url, notice: "Server part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server_part
      @server_part = ServerPart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def server_part_params
      params.require(:server_part).permit(:name)
    end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: %i[ show edit update destroy ]

  # GET /servers or /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1 or /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers or /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to server_url(@server), notice: "Server was successfully created." }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1 or /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to server_url(@server), notice: "Server was successfully updated." }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1 or /servers/1.json
  def destroy
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url, notice: "Server was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def server_params
      params.require(:server).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/server_corpus_helper.rb
module ServerCorpusHelper
end

app/helpers/server_parts_helper.rb
module ServerPartsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventarization</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/server_corpus/_form.html.erb
<%= form_with(model: server_corpu) do |form| %>
  <% if server_corpu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(server_corpu.errors.count, "error") %> prohibited this server_corpu from being saved:</h2>

      <ul>
        <% server_corpu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/server_corpus/_server_corpu.html.erb
<div id="<%= dom_id server_corpu %>">
  <p>
    <strong>Name:</strong>
    <%= server_corpu.name %>
  </p>

</div>

app/views/server_corpus/edit.html.erb
<h1>Editing server corpu</h1>

<%= render "form", server_corpu: @server_corpu %>

<br>

<div>
  <%= link_to "Show this server corpu", @server_corpu %> |
  <%= link_to "Back to server corpus", server_corpus_path %>
</div>

app/views/server_corpus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Server corpus</h1>

<div id="server_corpus">
  <% @server_corpus.each do |server_corpu| %>
    <%= render server_corpu %>
    <p>
      <%= link_to "Show this server corpu", server_corpu %>
    </p>
  <% end %>
</div>

<%= link_to "New server corpu", new_server_corpu_path %>

app/views/server_corpus/new.html.erb
<h1>New server corpu</h1>

<%= render "form", server_corpu: @server_corpu %>

<br>

<div>
  <%= link_to "Back to server corpus", server_corpus_path %>
</div>

app/views/server_corpus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @server_corpu %>

<%= link_to 'png', server_corpu_path(format: :png, id: @server_corpu.id) %>

<%= link_to 'tst', bind_part_server_corpu_path(id: @server_corpu.id, part_id: 1), method: :post %>

<table class="table">
  <% @server_corpu.server_server_parts.each do |server_part| %>
    <tr>
      <td>
        <%= server_part.created_at %>
      </td>
      <td>
        <%= server_part.server_part.name %>
      </td>
    </tr>
    <p></p>
  <% end %>
</table>
<div>
  <%= link_to "Edit this server corpu", edit_server_corpu_path(@server_corpu) %> |
  <%= link_to "Back to server corpus", server_corpus_path %>

  <%= button_to "Destroy this server corpu", @server_corpu, method: :delete %>
</div>

app/views/server_parts/_form.html.erb
<%= form_with(model: server_part) do |form| %>
  <% if server_part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(server_part.errors.count, "error") %> prohibited this server_part from being saved:</h2>

      <ul>
        <% server_part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/server_parts/_server_part.html.erb
<div id="<%= dom_id server_part %>">
  <p>
    <strong>Name:</strong>
    <%= server_part.name %>
  </p>

</div>

app/views/server_parts/edit.html.erb
<h1>Editing server part</h1>

<%= render "form", server_part: @server_part %>

<br>

<div>
  <%= link_to "Show this server part", @server_part %> |
  <%= link_to "Back to server parts", server_parts_path %>
</div>

app/views/server_parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Server parts</h1>

<div id="server_parts">
  <% @server_parts.each do |server_part| %>
    <%= render server_part %>
    <p>
      <%= link_to "Show this server part", server_part %>
    </p>
  <% end %>
</div>

<%= link_to "New server part", new_server_part_path %>

app/views/server_parts/new.html.erb
<h1>New server part</h1>

<%= render "form", server_part: @server_part %>

<br>

<div>
  <%= link_to "Back to server parts", server_parts_path %>
</div>

app/views/server_parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @server_part %>
<%= link_to 'png', server_part_path(format: :png, id: @server_part.id) %>

<div>
  <%= link_to "Edit this server part", edit_server_part_path(@server_part) %> |
  <%= link_to "Back to server parts", server_parts_path %>

  <%= button_to "Destroy this server part", @server_part, method: :delete %>
</div>

app/views/servers/_form.html.erb
<%= form_with(model: server) do |form| %>
  <% if server.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
        <% server.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/_server.html.erb
<div id="<%= dom_id server %>">
  <p>
    <strong>Name:</strong>
    <%= server.name %>
  </p>

</div>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render "form", server: @server %>

<br>

<div>
  <%= link_to "Show this server", @server %> |
  <%= link_to "Back to servers", servers_path %>
</div>

app/views/servers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Servers</h1>

<div id="servers">
  <% @servers.each do |server| %>
    <%= render server %>
    <p>
      <%= link_to "Show this server", server %>
    </p>
  <% end %>
</div>

<%= link_to "New server", new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render "form", server: @server %>

<br>

<div>
  <%= link_to "Back to servers", servers_path %>
</div>

app/views/servers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @server %>

<div>
  <%= link_to "Edit this server", edit_server_path(@server) %> |
  <%= link_to "Back to servers", servers_path %>

  <%= button_to "Destroy this server", @server, method: :delete %>
</div>